name: color_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  characters: ^1.1.0
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  solid_lints: ^0.1.4

flutter:
  uses-material-design: true
